apiVersion: operator.ibm.com/v1
kind: IBMServiceMeterDefinition
metadata:
  name: baw-cmis-metrics
  namespace: REPLACE_NAMESPACE
spec:
  mappingId: cmisdeployment000000000001
  processing: LAST
  repeat: true
  breakdownDefs:
    - breakdownBy:
        name: INSTANCE_COUNT
      groupBy:
        - componentId
        - componentName
        - version
        - environment
        - architecture
        - platform
        - cmis_inbound
        - cmis_document_upload
        - cmis_document_read
      source: metricQuantity
      processing: LAST
  data:
    componentId: 3191c7cdc4c8413dafaaad1f180e4ce8
    componentName: IBM ECM CMIS
    productId: 9c2d4f167cdb411fa3b1d787eb3c7c34
    productName: IBM Content Cortex
    metricName: INSTANCE_COUNT
    metricDescription: count of CMIS instances
    metricType: ADOPTION
