################################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2019. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
# CP4BA 2500.SP07 catalog
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cp4a-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cp4a-operator
  publisher: IBM
  sourceType: grpc
  image: cp.stg.icr.io/cp/ibm-cp-automation-catalog@sha256:648bfc27dd8542d989c551ead72ef53741cc501a930db00a6201cb35e536f487
  secrets:
  - "ibm-entitlement-key"
  - "ibm-stg-entitlement-key"
  grpcPodConfig:
    securityContextConfig: restricted
  updateStrategy:
    registryPoll:
      interval: 45m
---
# IBM CS Flink Operator Catalog 1.18.1 (2.0.4)
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-opencontent-flink
  namespace: openshift-marketplace
spec:
  displayName: IBM CS Opencontent Flink Catalog
  publisher: IBM
  sourceType: grpc
  image: >-
    icr.io/cpopen/ibm-opencontent-flink-operator-catalog@sha256:b1e6182101793348aaf45b77160848b09674033a2b6c910d14d3049a711bbdd7
  secrets:
  - "ibm-entitlement-key"
  - "ibm-stg-entitlement-key"
  grpcPodConfig:
    securityContextConfig: restricted
  updateStrategy:
    registryPoll:
      interval: 45m
  priority: 100
---
# IBM CS Opensearch Operator Catalog 1.1.1714
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-opensearch-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: IBM CS Opencontent Opensearch Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/opencontent-ibm-opensearch-operator-catalog@sha256:426d27d1fac806db94782e4017e92ca570113af674a7bb203fd1433aa7a72bb7
  secrets:
  - "ibm-entitlement-key"
  - "ibm-stg-entitlement-key"
  grpcPodConfig:
    securityContextConfig: restricted
  updateStrategy:
    registryPoll:
      interval: 45m
  priority: 100
---
# IBM Certificate Manager 4.2.13
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cert-manager-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cert-manager-4.2.13
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-cert-manager-operator-catalog@sha256:21866a45719eef50764c421c349a539262147d215ef87c8cc2174fdf2c269346
  secrets:
  - "ibm-entitlement-key"
  - "ibm-stg-entitlement-key"
  grpcPodConfig:
    securityContextConfig: restricted
  updateStrategy:
    registryPoll:
      interval: 45m
---
# IBM License Manager 4.2.13
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-licensing-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-licensing-4.2.13
  publisher: IBM
  image: icr.io/cpopen/ibm-licensing-catalog@sha256:17980ccacb1aeae19729e7d5129ad0b69e0f18a2c30f9f1a0db1daf9ae7c2e92
  sourceType: grpc
  secrets:
  - "ibm-entitlement-key"
  - "ibm-stg-entitlement-key"
  grpcPodConfig:
    securityContextConfig: restricted
  updateStrategy:
    registryPoll:
      interval: 45m
---
# IBM Cloud Foundational Services 4.12.0
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cs-install-catalog-v4-12-0
  namespace: openshift-marketplace
  annotations:
    bedrock_catalogsource_priority: '1'
spec:
  displayName: IBM CS Install Operators
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-cs-install-catalog@sha256:d875123a9f01fed953036065c81131b5e1ebfc4f89047df876f90cf5d12cc00f
  secrets:
  - "ibm-entitlement-key"
  - "ibm-stg-entitlement-key"
  grpcPodConfig:
    securityContextConfig: restricted
  updateStrategy:
    registryPoll:
      interval: 45m
  priority: 100    
---
# IBM Business Teams Service version 3.35.3
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-bts-operator-catalog-v3-35-3
  namespace: openshift-marketplace
  annotations:
    bedrock_catalogsource_priority: '1'
spec:
  displayName: BTS Operator-3.35.3
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-bts-operator-catalog@sha256:c563064724730eca3e186ceedf295b0db14afa1ef4ba5ae21339193c4bb8358c
  secrets:
  - "ibm-entitlement-key"
  - "ibm-stg-entitlement-key"
  grpcPodConfig:
    securityContextConfig: restricted
  updateStrategy:
    registryPoll:
      interval: 45m
---
# IBM CS IM Operator Catalog 4.11.0
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-iam-operator-catalog-4-11-0
  namespace: openshift-marketplace
  annotations:
    bedrock_catalogsource_priority: '1'
spec:
  displayName: IBM IAM Operator Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-iam-operator-catalog@sha256:412a1941301da0adcfb0e2213e14eca7e01f1dbbe416db72d1c9b26c2abc6cee
  secrets:
  - "ibm-entitlement-key"
  - "ibm-stg-entitlement-key"
  grpcPodConfig:
    securityContextConfig: restricted
  updateStrategy:
    registryPoll:
      interval: 45m
  priority: 100
---
# IBM Zen Operator Catalog 6.1.3+20250327.140337.10
# we only update the catalog name when the channel is changed.
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-zen-operator-catalog-6-1-0
  namespace: openshift-marketplace
  annotations:
    bedrock_catalogsource_priority: '1'
spec:
  displayName: IBM Zen Operator Catalog
  publisher: IBM
  sourceType: grpc
  image: cp.stg.icr.io/cp/ibm-zen-operator-catalog@sha256:8aa614c2538ddb65c2df4b5eabb208272f3026136772cbe3af7d26ba283aba34
  secrets:
  - "ibm-entitlement-key"
  - "ibm-stg-entitlement-key"
  grpcPodConfig:
    securityContextConfig: restricted
  updateStrategy:
    registryPoll:
      interval: 45m
  priority: 100
---
# IBM Events Operator Catalog 5.1.2
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-events-operator-catalog-v5-1-0
  namespace: openshift-marketplace
  annotations:
    bedrock_catalogsource_priority: '1'
spec:
  displayName: IBM Events Operator Catalog-v5.1.2
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-events-operator-catalog@sha256:603a6bf0e616f16b609bf157b9e21415802478aefc9c606e124008d0224a1188
  secrets:
  - "ibm-entitlement-key"
  - "ibm-stg-entitlement-key"
  grpcPodConfig:
    securityContextConfig: restricted
  updateStrategy:
    registryPoll:
      interval: 45m
  priority: 100
---
# Cloud Native PostgresSQL Version 1.25.1 (CASE 5.15.0+20250416.103820.2490)(Postgresql Image Version 14.17)
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cloud-native-postgresql-catalog
  namespace: openshift-marketplace
  annotations:
    bedrock_catalogsource_priority: '1'
spec:
  displayName: Cloud Native Postgresql Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-cpd-cloud-native-postgresql-operator-catalog@sha256:7dbff355db7739152961cb6a97887d2e43bc960ac58837c126e03ed1a4480a3a
  secrets:
  - "ibm-entitlement-key"
  - "ibm-stg-entitlement-key"
  grpcPodConfig:
    securityContextConfig: restricted
  updateStrategy:
    registryPoll:
      interval: 45m
  priority: 100
---
# IBM FileNet Content Manager Standalone catalog for 5.7.0
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-fncm-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-fncm-operator
  publisher: IBM
  sourceType: grpc
  image: cp.stg.icr.io/cp/ibm-fncm-catalog@sha256:d5d36faa1156fb03a776be5a2ef7761f82851c753b94b71c93111ecbcc56e6c6
  secrets:
  - "ibm-entitlement-key"
  - "ibm-stg-entitlement-key"
  grpcPodConfig:
    securityContextConfig: restricted
  updateStrategy:
    registryPoll:
      interval: 45m
