################################################################################
#
# Licensed Materials - Property of IBM
#
# (C) Copyright IBM Corp. 2019. All Rights Reserved.
#
# US Government Users Restricted Rights - Use, duplication or
# disclosure restricted by GSA ADP Schedule Contract with IBM Corp.
#
###############################################################################
# CP4BA 25.0.0-IF003 catalog
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cp4a-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cp4a-operator
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-cp-automation-catalog@sha256:5e85d9b4c5c566781c3285c39c237dd458f86ed704c9f629e718eb268c7ea36d
  secrets:
  - "ibm-entitlement-key"
  grpcPodConfig:
    securityContextConfig: restricted
---
# IBM CS Flink Operator Catalog 1.18.1 (2.0.5+20250528.100000)
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-opencontent-flink
  namespace: openshift-marketplace
spec:
  displayName: IBM CS Opencontent Flink Catalog
  publisher: IBM
  sourceType: grpc
  image: >-
    icr.io/cpopen/ibm-opencontent-flink-operator-catalog@sha256:452a16bfe1f015ac3a5510874a4b20bb0488caa5d74b270b608c2571b17b97ac
  secrets:
  - "ibm-entitlement-key"
  grpcPodConfig:
    securityContextConfig: restricted
  priority: 100
---
# IBM CS Opensearch Operator Catalog 1.1.4005
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-opensearch-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: IBM CS Opencontent Opensearch Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/opencontent-ibm-opensearch-operator-catalog@sha256:7ff897a206d020b973949df4176be388f5d19a27595937e3a43ec34a9f78711e
  secrets:
  - "ibm-entitlement-key"
  grpcPodConfig:
    securityContextConfig: restricted
  priority: 100
---
# IBM Certificate Manager 4.2.18
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cert-manager-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-cert-manager-4.2.18
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-cert-manager-operator-catalog@sha256:78e1242e197ed1a2db82ea29887ff85b77ce39d15868fd26505fcfe7db0c3bba
  secrets:
  - "ibm-entitlement-key"
  grpcPodConfig:
    securityContextConfig: restricted
---
# IBM License Manager 4.2.18
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-licensing-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-licensing-4.2.18
  publisher: IBM
  image: icr.io/cpopen/ibm-licensing-catalog@sha256:42e8f5a12742742c1967568d497ff1c93aa7a78a3a7ad414da011d0c1eedb19a
  sourceType: grpc
  secrets:
  - "ibm-entitlement-key"
  grpcPodConfig:
    securityContextConfig: restricted
---
# IBM Cloud Foundational Services 4.16.0
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-cs-install-catalog-v4-16-0
  namespace: openshift-marketplace
  annotations:
    bedrock_catalogsource_priority: '1'
spec:
  displayName: IBM CS Install Operators
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-cs-install-catalog@sha256:f24bad596f32cc6531420c8533419d6b7bc5c65da5578ab9ca6e55180cd72ac5
  secrets:
  - "ibm-entitlement-key"
  grpcPodConfig:
    securityContextConfig: restricted
  priority: 100 
---
# IBM Business Teams Service version 3.35.7
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-bts-operator-catalog-v3-35
  namespace: openshift-marketplace
  annotations:
    bedrock_catalogsource_priority: '1'
spec:
  displayName: BTS Operator-3.35.7
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-bts-operator-catalog@sha256:9a2e253c3a4931c579882ba791544f5afd0283a465c2c398e5b22f7416154d6d
  secrets:
  - "ibm-entitlement-key"
  grpcPodConfig:
    securityContextConfig: restricted
---
# IBM CS IM Operator Catalog 4.15.0
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-iam-operator-catalog-4-15-0
  namespace: openshift-marketplace
  annotations:
    bedrock_catalogsource_priority: '1'
spec:
  displayName: IBM IAM Operator Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-iam-operator-catalog@sha256:620c8985b5e6056082a5e0aa35a91e1de7aeb15145690a4683bd80a32b3e4fa6
  secrets:
  - "ibm-entitlement-key"
  grpcPodConfig:
    securityContextConfig: restricted
  priority: 100
---
# IBM Zen Operator Catalog 6.3.0+20251128.181612.335
# we only update the catalog name when the channel is changed.
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-zen-operator-catalog-6-3-0
  namespace: openshift-marketplace
  annotations:
    bedrock_catalogsource_priority: '1'
spec:
  displayName: IBM Zen Operator Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-zen-operator-catalog@sha256:e6d5f076f9600e093cd2a66e2b5147d39dffdeb81564a2672d315b3ccb913593
  secrets:
  - "ibm-entitlement-key"
  grpcPodConfig:
    securityContextConfig: restricted
  priority: 100
---
# IBM Events Operator Catalog 5.2.1
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-events-operator-catalog-v5-2-1
  namespace: openshift-marketplace
  annotations:
    bedrock_catalogsource_priority: '1'
spec:
  displayName: IBM Events Operator Catalog-v5.2.1
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-events-operator-catalog@sha256:228ea92d69daa2350e151d1fe6b14e6fb56eadd0d3b5b5872178180747297687
  secrets:
  - "ibm-entitlement-key"
  grpcPodConfig:
    securityContextConfig: restricted
  priority: 100
---
# Cloud Native PostgresSQL Version 1.25.4 (CASE 5.30.0+20251030.101847.2667)(Postgresql Image Version 14.19)
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: cloud-native-postgresql-catalog
  namespace: openshift-marketplace
  annotations:
    bedrock_catalogsource_priority: '1'
spec:
  displayName: Cloud Native Postgresql Catalog
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-cpd-cloud-native-postgresql-operator-catalog@sha256:64319d2ce95721f25bbafb952af06e65f635097b04b1b5ecc4631b2757f6201d
  secrets:
  - "ibm-entitlement-key"
  grpcPodConfig:
    securityContextConfig: restricted
  priority: 100
---
# IBM FileNet Content Manager Standalone catalog for 5.7.0-IF001
apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:
  name: ibm-fncm-operator-catalog
  namespace: openshift-marketplace
spec:
  displayName: ibm-fncm-operator
  publisher: IBM
  sourceType: grpc
  image: icr.io/cpopen/ibm-fncm-catalog@sha256:86a3e1aa7de5ad5e45ab56c69c25692661447b58360ab9add0ff6182f4545d3e
  secrets:
  - "ibm-entitlement-key"
  grpcPodConfig:
    securityContextConfig: restricted
